# Generated by Django 5.2.1 on 2025-05-23 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='토픽 이름')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='파일 이름')),
                ('extension', models.CharField(max_length=10, verbose_name='확장자')),
                ('path', models.TextField(verbose_name='파일 경로')),
                ('rate', models.IntegerField(verbose_name='샘플링 레이트 (Hz)')),
                ('bit_depth', models.IntegerField(verbose_name='비트 깊이')),
                ('channels', models.IntegerField(verbose_name='채널 수')),
                ('duration', models.BigIntegerField(verbose_name='전체 프레임 수')),
                ('min_freq', models.IntegerField(verbose_name='최소 주파수 (Hz)')),
                ('max_freq', models.IntegerField(verbose_name='최대 주파수 (Hz)')),
                ('rms_loud', models.FloatField(verbose_name='평균 음량 RMS')),
                ('zero_cross', models.BigIntegerField(verbose_name='영점 교차 프레임 수')),
                ('spec_cent', models.BigIntegerField(verbose_name='스펙트럼 무게중심 프레임 수')),
                ('spec_bw', models.BigIntegerField(verbose_name='스펙트럼 대역폭 프레임 수')),
                ('spec_flat', models.BigIntegerField(verbose_name='스펙트럼 평탄도 프레임 수')),
                ('rolloff', models.BigIntegerField(verbose_name='롤-오프 프레임 수')),
                ('chroma_stft', models.JSONField(verbose_name='크로마 STFT (12d per frame)')),
                ('spec_contr', models.JSONField(verbose_name='스펙트럴 대비')),
                ('tonnetz', models.JSONField(verbose_name='Tonnetz 특성')),
                ('mfcc', models.JSONField(verbose_name='MFCC 계수 0~13')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='통화 요약 텍스트')),
                ('conflict', models.BooleanField(choices=[(False, '없음'), (True, '있음')], default=False, verbose_name='갈등 플래그')),
                ('silence', models.BigIntegerField(verbose_name='침묵 프레임 수')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='분석 시각')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='callytics.topic', verbose_name='관련 토픽')),
            ],
        ),
        migrations.CreateModel(
            name='Utterance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaker', models.CharField(choices=[('agent', 'agent'), ('customer', 'customer')], max_length=10, verbose_name='발화자')),
                ('sequence', models.IntegerField(verbose_name='발화 순번')),
                ('start_time', models.BigIntegerField(verbose_name='시작 프레임 번호')),
                ('end_time', models.BigIntegerField(verbose_name='종료 프레임 번호')),
                ('content', models.TextField(verbose_name='발화 내용')),
                ('sentiment', models.CharField(max_length=10, verbose_name='감정 레이블')),
                ('profane', models.BooleanField(default=False, verbose_name='비속어 플래그')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='callytics.file', verbose_name='관련 파일')),
            ],
        ),
    ]
